                                              name: Auto Refresh B2-TEAM Repository

on:
  schedule:
    - cron: '0 */1 * * *' # يشغل الكود كل ساعة
  push: # عند كل عملية دفع جديدة
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # الخطوة 1: تنزيل المستودع
      - name: Checkout Repository
        uses: actions/checkout@v3

      # الخطوة 2: إعداد Git
      - name: Configure Git
        run: |
          git config user.name "gasem_hany" # استبدل باسم المستخدم الخاص بك
          git config user.email "gasemar684@gmail.com" # استبدل بالبريد الإلكتروني الخاص بك
          git remote set-url origin https://${{ secrets.B2 }}@github.com/gasemhany/B2-TEAM.git
      # الخطوة 3: تحديث المستودع ودفع التعديلات
      - name: Pull and Push Changes
        run: |
          echo "Executing auto-refresh tasks..."
          git config pull.rebase false  # تفعيل الدمج الافتراضي لتجنب المشاكل
          git pull origin main          # جلب التغييرات من الفرع الرئيسي
          git push origin main          # دفع التحديثات مرة أخرى
